### PR TITLE
CON-49424: Update Alice's scripts with her latest version.

### PR DESCRIPTION
**Pull request by msimon-jama**
Update Alice's scripts with her latest version.

### CODE REVIEW

**Review by hmecelis — APPROVED** [review]
LGTM

**Review by hmecelis-jama — APPROVED** [review]
LGTM

**Review by hmecelis-jama — APPROVED** [review]

**Review by jblaine-jama — APPROVED** [review]
reviewed go go go

**Review by afong-jama — APPROVED** [review]
👍

**Review by jblaine-jama — APPROVED** [review]
approve

**Review by rrmoore-Jama — APPROVED** [review]

**Review by jblaine-jama — APPROVED** [review]

**Review by hmecelis-jama — APPROVED** [review]
LGTM

**Review by jskaggs-jama — APPROVED** [review]

**Review by reast-jama — APPROVED** [review]
test

**Review by cguzman-jama — APPROVED** [review]
I took a look at this per @jblaine-jama's ask and the changes does not seem related to https://csejamasoftware.atlassian.net/browse/CON-49424. Leaving that aside, the changes seem to include `zzjama` and `con` tables when checking collation, which should be ok. So, I am approving this. However, I don't have write access to this repo so my approval might not allow the merge.

**Comment by jblaine-jama** [comment]
Merging.

**Pull request merged**
